#define KSTR001 "                                         "
#define KSTR002 "           &&&&&&&&&&&&&&                "
#define KSTR003 "      &&&&&&&&X&      &&&:x&&            "
#define KSTR004 "    x  ;X&x $. $. &&&&&+$&&+.X           "
#define KSTR005 "    &&&&; x&+   ;$.            +         "
#define KSTR006 "    x  &&&  X&&&&;&&&&&&&&&&&&& X&       "
#define KSTR007 "   &X&&&  &&&&&&&&&X&&+&&&&x$&$$& :      "
#define KSTR008 " &&+&& +&&.      ..:;X&$XxxxX;+: &&      "
#define KSTR009 " &&;&&;                 . ..;:;+: &:     "
#define KSTR010 " && &; :             .   .;:;;:++  &     "
#define KSTR011 " &&;&.&X.       :.   ......::;;+;        "
#define KSTR012 "  x&&;$+   ..   .:;+;;:;:::;+++; x.      "
#define KSTR013 "  &+ ;+;    .:;;;.::.:. ;+x+;.   .       "
#define KSTR014 "  &$x;+;               ;:;::.;&&&&&&     "
#define KSTR015 "   :$:       +&&&&&&$.     ;+.    .      "
#define KSTR016 "  +&&     .XX        .        &&&&&&&&&& "
#define KSTR017 "  &  &&&;     &&&&&&&&&&&&&&&&&&x     .. "
#define KSTR018 "  &x&$   &&&&&&&&& .&&.&&&$ &:&x+.    :  "
#define KSTR019 "   +&&    &&    .;+&&+ &&   &  :+xx  .   "
#define KSTR020 "    &:     &  .:.:;.  :&x    &; :;&&;    "
#define KSTR021 "     +&     &         &.  :;  &&&;.      "
#define KSTR022 "       :      &&&&&&&&: : . ;   $:x      "
#define KSTR023 "        x  .        ;&  .   + $&&$&      "
#define KSTR024 "         &    .:..;+:;;&&&&xx&.   x      "
#define KSTR025 "          &    .:::    .;&x&X&&&&&       "
#define KSTR026 "           X  :..  :&&&&&X:x:. x&&&      "
#define KSTR027 "           &&+   :&&&&&&&&&&&&$  +&      "
#define KSTR028 "            &&x   &.         :  ;&&      "
#define KSTR029 "             &&&&&&   :XX&&&&x   &       "
#define KSTR030 "               &&&&&&:          $;       "
#define KSTR031 "                 &&&&&&X;+;&$&&&         "
#define KSTR032 "                    &&&&&&&&&&&          "
#define KSTR033 "                                         "

#define KSTR113 "  &+ ;+;    .:;;;.::.:. ;+x+;.&&&&&&     "
#define KSTR114 "  &$x;+;      &&&&&&$  ;:;::.;           "
#define KSTR115 "   :$:       +       .     ;+.    .      "
